from datetime import datetime
from models.settings import db


class Character(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    height = db.Column(db.Integer, nullable=True)
    mass = db.Column(db.Integer, nullable=True)
    wiki = db.Column(db.String, nullable=True)
    image = db.Column(db.String, nullable=True)
    born = db.Column(db.Integer, nullable=True)
    bornLocation = db.Column(db.String, nullable=True)
    died = db.Column(db.Integer, nullable=True)
    diedLocation = db.Column(db.String, nullable=True)
    dateCreated = db.Column(db.Integer, nullable=True)
    dateDestroyed = db.Column(db.Integer, nullable=True)
    destroyedLocation = db.Column(db.String, nullable=True)
    creator_id = db.Column(db.Integer, db.ForeignKey('character.id'), nullable=True)
    creator = db.relationship("Character")
    manufacturer_id = db.Column(db.Integer, db.ForeignKey('manufacturer.id'), nullable=True)
    manufacturer = db.relationship("Manufacturer")
    model_id = db.Column(db.Integer, db.ForeignKey('model.id'), nullable=True)
    model = db.relationship("Model")
    classType_id = db.Column(db.Integer, db.ForeignKey('class.id'), nullable=True)
    classType = db.relationship("Class")
    sensorColor_id = db.Column(db.Integer, db.ForeignKey('sensorColor.id'), nullable=True)
    sensorColor = db.relationship("sensorColor")
    platingColor_id = db.Column(db.Integer, db.ForeignKey('platingColor.id'), nullable=True)
    platingColor = db.relationship("PlatingColor")
    productLine_id = db.Column(db.Integer, db.ForeignKey('productLine.id'), nullable=True)
    productLine = db.relationship("ProductLine")
    kajidic = db.Column(db.String, nullable=True)
    degree_id = db.Column(db.Integer, db.ForeignKey('degree.id'), nullable=True)
    degree = db.relationship("Degree")
    hairColor = db.Column(db.String, nullable=True)
    eyeColor = db.Column(db.String, nullable=True)
    skinColor = db.Column(db.String, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)
